<a href="https://colab.research.google.com/github/annLiu310/python-basic/blob/master/03_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.  

In [0]:

 #Using Numpy
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [9]:
import numpy as np
list_numpy = list(range(1,4))
print(list_numpy)

# cast a list to array
array_list = np.array(list_Numpy)
print(array_list)

matrix_numpy = [[1,2,3],[4,5,6],[7,8,9]]
array_matrix = np.array(matrix_numpy)
print(array_matrix)
array_matrix

[1, 2, 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange      (range)

start,  end,  step

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones matrix

Generate arrays of zeros or ones

In [0]:
# np.zeros(dimension)
np.zeros(3)

array([ 0.,  0.,  0.])

In [0]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [0]:
np.ones(3)

array([ 1.,  1.,  1.])

In [0]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:

#Return evenly spaced numbers over a specified interval.
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [0]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [0]:
# Create indentity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.


概率相等, 连续均匀分布



In [16]:
np.random.rand(2)

array([0.67575324, 0.57005567])

In [17]:
np.random.rand(5,5) #tuple 

array([[0.32534602, 0.70121865, 0.11017187, 0.07459125, 0.00452218],
       [0.98384352, 0.71537754, 0.32656226, 0.9724161 , 0.96169697],
       [0.43261309, 0.49570617, 0.26718002, 0.07288036, 0.79306561],
       [0.04766489, 0.36297764, 0.14358327, 0.29832013, 0.08893205],
       [0.20521645, 0.13987685, 0.33760029, 0.9150385 , 0.41476953]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

正太 高斯分布


In [18]:
np.random.randn(2)

array([ 0.39679028, -1.97923203])

In [19]:
np.random.randn(5,5)

array([[ 0.92018844, -0.56368028,  0.20239085,  0.08108795,  0.11143113],
       [ 0.3596689 ,  0.3804121 , -0.45852344, -0.03683451, -0.24662691],
       [-0.99212148,  0.78516614,  0.15361486,  0.21316189, -0.26414625],
       [ 0.65261373,  1.91250654,  0.91843798, -0.55203306, -0.53826332],
       [ 0.72252302,  0.79434218, -0.22672881,  0.71741517, -1.46137367]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.randint(1,100)

23

In [0]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Array Attributes and Methods

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([31, 32,  0,  0, 30, 46, 48, 32, 18, 41])

## Reshape
Returns an array containing the same data with a new shape.

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [27]:
ranarr

array([31, 32,  0,  0, 30, 46, 48, 32, 18, 41])

In [28]:
# max in array
ranarr.max()

48

In [29]:
# index location of max array
ranarr.argmax()

6

In [0]:
ranarr.min()

2

In [32]:
# index location of min array
ranarr.argmin() 

2

## Shape

Shape is an attribute that arrays have (not a method):

In [33]:
# Vector
arr.shape

(25,)

In [0]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25,1).shape

(25, 1)

### dtype

  grab the data type of the object in the array:

In [0]:
arr.dtype

dtype('int64')